### ISSUE TITLE
A structure of the database

### ISSUE THREAD

**Issue by paulouskunda** [abhishekvirat0/Food_Ordering_App#3]
To fully see the power of the app, a structure of the database is need sir.

**Comment by abhishekvirat0** [comment]
I have already added a screenshot of firebase database structure.please look in readme.md file.

**Comment by jeffwiy** [comment]
Hi,
Could you provide all the firebase database structure?
The screenshot only shows partial structure.
I'm stuck trying to display food menus inside the category. I think the information above will help me.
Thanks.

**Comment by jeffwiy** [comment]
Category
ㄴ01
&zwnj; &zwnj; &zwnj; &zwnj;ㅣ Image
&zwnj; &zwnj; &zwnj; &zwnj; &zwnj;ㄴName
Foods
ㄴ 01
&zwnj; &zwnj; &zwnj; &zwnj;ㅣ Description
&zwnj; &zwnj; &zwnj; &zwnj;ㅣ Discount
&zwnj; &zwnj; &zwnj; &zwnj;ㅣ Image
&zwnj; &zwnj; &zwnj; &zwnj;ㅣ MenuId
&zwnj; &zwnj; &zwnj; &zwnj;ㅣ Name
&zwnj; &zwnj; &zwnj; &zwnj; &zwnj;ㄴPrice
